default:
  suites:
    default:
      paths:
        - features
      contexts:
        - PaulGibbs\WordpressBehatExtension\Context\WordpressContext
        - FeatureContext
        - Behat\MinkExtension\Context\MinkContext
        - PaulGibbs\WordpressBehatExtension\Context\ContentContext
        - PaulGibbs\WordpressBehatExtension\Context\DashboardContext
        - PaulGibbs\WordpressBehatExtension\Context\SiteContext
        - PaulGibbs\WordpressBehatExtension\Context\UserContext
        - PaulGibbs\WordpressBehatExtension\Context\EditPostContext
        - PaulGibbs\WordpressBehatExtension\Context\WidgetContext
        - PaulGibbs\WordpressBehatExtension\Context\ToolbarContext

  extensions:
    Behat\MinkExtension:
      base_url: http://passwords-evolved.test
      default_session: default
      sessions:
        default:
          goutte:
            guzzle_parameters:
              verify: false

    PaulGibbs\WordpressBehatExtension:
      default_driver: wpcli
      path: vendor/bin/wp
      users:
        admin:
          username: admin
          password: password
